/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

//  module.exports = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   sidebar: [
//     // "index"
//     {
//       type: "category",
//       label: "开始入门 ( Getting Started )",
//       collapsed: false,
//       collapsible: false,
//       items: [{ type: "autogenerated", dirName: "get_started" }],
//     },
//     {
//       type: "category",
//       label: "核心模块 ( Components )",
//       collapsed: false,
//       collapsible: false,
//       items: [{ type: "autogenerated", dirName: "modules" }],
//     },
//     {
//       type: "category",
//       label: "生态 ( Ecosystem )",
//       items: [{ type: "autogenerated", dirName: "ecosystem" }],
//     }
//   ],
// };


module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebar: [
    "index",
    // {
    //   type: "html",
    //   value: "<h3>Langchain Python</h3><hr>",
    //   defaultStyle: true,
    // },
    {
      type: "category",
      label: " 入门 ( Get started )",
      collapsed: false,
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "get_started" }],
      link: {
        type: 'generated-index',
        description: 'LangChain 入门教程',
	    slug: "get_started",
      },
    },
    {
      type: "category",
      label: "核心模块 ( Modules )",
      collapsed: false,
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "modules" } ],
      link: {
        type: 'doc',
        id: "modules/index"
      },
    },
    {
      type: "category",
      label: "用例 ( Use cases )",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "use_cases" }],
      link: {
        type: 'generated-index',
        description: 'LangChain 用户案例集',
	    slug: "use_cases",
      },
    },
    {
      type: "category",
      label: "指南 ( Guides )",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "guides" }],
      link: {
        type: 'generated-index',
        description: 'LangChain 设计指南助力开发者更快开发',
	    slug: "guides",
      },
    },
    {
      type: "category",
      label: "生态  ( Ecosystem )",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "ecosystem" }],
      link: {
        type: 'generated-index',
	    slug: "ecosystem",
      },
    },
    {
      type: "category",
      label: "资源  ( Additional resources )",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "additional_resources" }, { type: "link", label: "Gallery", href: "https://github.com/kyrolabs/awesome-langchain" }],
      link: {
        type: 'generated-index',
	      slug: "additional_resources",
      },
    },
    {
       type: "link",
       href: "https://api.python.langchain.com",
       label: "API reference",
    },
    {
      type: "html",
      value: '<img src="https://pic1.zhimg.com/80/v2-31131dcb1732cb5bca7c182c9e8da046_r.jpg" alt="扫我，入群" width="280" height="330"/>'
    }
  ],
};
